// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcSH_Des3IKwh5vJMrpcxYkfLd3lA2sk',
    appId: '1:570108377809:web:308273e498503d16c3a3f0',
    messagingSenderId: '570108377809',
    projectId: 'appweater',
    authDomain: 'appweater.firebaseapp.com',
    storageBucket: 'appweater.firebasestorage.app',
    measurementId: 'G-QNM4N09QNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQpscnjwFMn7wvHxbFXmSgm543dFlg78',
    appId: '1:570108377809:android:00436f95f9dacb1bc3a3f0',
    messagingSenderId: '570108377809',
    projectId: 'appweater',
    storageBucket: 'appweater.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxtnC5yYKgsXDdW96FE1CydW6gyoGZGQ',
    appId: '1:570108377809:ios:c6bedd6733b3aae2c3a3f0',
    messagingSenderId: '570108377809',
    projectId: 'appweater',
    storageBucket: 'appweater.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuxtnC5yYKgsXDdW96FE1CydW6gyoGZGQ',
    appId: '1:570108377809:ios:c6bedd6733b3aae2c3a3f0',
    messagingSenderId: '570108377809',
    projectId: 'appweater',
    storageBucket: 'appweater.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhcSH_Des3IKwh5vJMrpcxYkfLd3lA2sk',
    appId: '1:570108377809:web:ecbbe47375293329c3a3f0',
    messagingSenderId: '570108377809',
    projectId: 'appweater',
    authDomain: 'appweater.firebaseapp.com',
    storageBucket: 'appweater.firebasestorage.app',
    measurementId: 'G-EKVYM65C97',
  );
}
